#include "StockHistory.h"
#include "BatchSystem.h"
#include "CutSticks.h"
#include "TwoStringMasks.h"
#include "InfiniteSequence2.h"
#include "FloorBoards.h"
#include "SortingGame.h"
#include "CountExpressions.h"
#include "AvoidingProduct.h"
#include "FIELDDiagrams.h"
#include "RevealTriangle.h"
#include "RelativePath.h"
#include "SymmetricPie.h"
#include "CorporationSalary.h"
#include "RodCut.h"
#include "OlympicCandles.h"
#include "OrderedSuperString.h"
using namespace std;
template<typename T>
void display(vector<T> left, vector<T> right) {
	if (left.size() != right.size()) {

		cout << "Deferent size!!!!\n";
		return;
	}
	bool fail = false;
	for (size_t i = 0; i < left.size(); i++)
	{
		if (left[i] != right[i]) {
			cout << "left :" << left[i] << " right : " << right[i] << "\n";
			fail = true;
		}
	}
	if (!fail)cout << "Success!!!!!\n"; 
}
int main() {
	OrderedSuperString oss;
	cout << oss.getLength({ "ab", "cd", "c", "ab" }) << " : 6\n";

	cout << oss.getLength({ "ababa", "ababd" }) << " : 7\n";

	cout << oss.getLength({ "a", "a", "b", "a" }) << " : 3\n";
	cout << oss.getLength({ "abc", "ca" }) << " : 4\n";
	cout << oss.getLength({ "abcdef", "ab", "bc", "de", "ef" }) << " : 6\n";
	cout << oss.getLength({ "ab", "bc", "de", "ef", "abcdef" }) << " : 12\n";
	cout << oss.getLength({ "a" }) << " : 1\n";
	cout << oss.getLength({ "bc", "abc" }) << " : 5\n";
	cout << oss.getLength({ "ab", "abc" }) << " : 3\n";
	cout << oss.getLength({ "aaaaaaaaaaabaaaaaaaa", "bac", "aaaabacaaa", "ab", "ba", "a", "ca" }) << " : 33\n";
	cout << oss.getLength({ "abcd", "bc", "ba" }) << " : 6\n";
	cout << oss.getLength({ "aaaaaaaaaa", "a", "ab", "a", "abbbb" }) << " : 14\n";
	cout << oss.getLength({ "bcdefgh", "b", "b", "b", "bc", "cd", "g", "gaa" }) << " : 10\n";
	cout << oss.getLength({ "x", "w", "v", "u", "t", "s", "r", "q", "p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a", "z", "y", "x", "w", "v", "u", "t", "s", "r", "q", "p", "o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a" }) << " : 50\n";
	cout << oss.getLength({ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }) << " : 50\n";
	cout << oss.getLength({ "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }) << " : 50\n";
	cout << oss.getLength({ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac" }) << " : 2500\n";
	cout << oss.getLength({ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaa", "aaaaaaaaaaaaaa", "aaaaaaaaaaaaa", "aaaaaaaaaaaa", "aaaaaaaaaaa", "aaaaaaaaaa", "aaaaaaaaa", "aaaaaaaa", "aaaaaaa", "aaaaaa", "aaaaa", "aaaa", "aaa", "aa", "a" }) << " : 50\n";
	cout << oss.getLength({ "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvw", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnop", "abcdefghijklmnopqrstuvwxyzabcdefghijklmno", "abcdefghijklmnopqrstuvwxyzabcdefghijklmn", "abcdefghijklmnopqrstuvwxyzabcdefghijklm", "abcdefghijklmnopqrstuvwxyzabcdefghijkl", "abcdefghijklmnopqrstuvwxyzabcdefghijk", "abcdefghijklmnopqrstuvwxyzabcdefghij", "abcdefghijklmnopqrstuvwxyzabcdefghi", "abcdefghijklmnopqrstuvwxyzabcdefgh", "abcdefghijklmnopqrstuvwxyzabcdefg", "abcdefghijklmnopqrstuvwxyzabcdef", "abcdefghijklmnopqrstuvwxyzabcde", "abcdefghijklmnopqrstuvwxyzabcd", "abcdefghijklmnopqrstuvwxyzabc", "abcdefghijklmnopqrstuvwxyzab", "abcdefghijklmnopqrstuvwxyza", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxy", "abcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvw", "abcdefghijklmnopqrstuv", "abcdefghijklmnopqrstu", "abcdefghijklmnopqrst", "abcdefghijklmnopqrs", "abcdefghijklmnopqr", "abcdefghijklmnopq", "abcdefghijklmnop", "abcdefghijklmno", "abcdefghijklmn", "abcdefghijklm", "abcdefghijkl", "abcdefghijk", "abcdefghij", "abcdefghi", "abcdefgh", "abcdefg", "abcdef", "abcde", "abcd", "abc", "ab", "a" }) << " : 50\n";
	cout << oss.getLength({ "a", "ab", "abc", "abcd", "abcde", "abcdef", "abcdefg", "abcdefgh", "abcdefghi", "abcdefghij", "abcdefghijk", "abcdefghijkl", "abcdefghijklm", "abcdefghijklmn", "abcdefghijklmno", "abcdefghijklmnop", "abcdefghijklmnopq", "abcdefghijklmnopqr", "abcdefghijklmnopqrs", "abcdefghijklmnopqrst", "abcdefghijklmnopqrstu", "abcdefghijklmnopqrstuv", "abcdefghijklmnopqrstuvw", "abcdefghijklmnopqrstuvwx", "abcdefghijklmnopqrstuvwxy", "abcdefghijklmnopqrstuvwxyz", "abcdefghijklmnopqrstuvwxyza", "abcdefghijklmnopqrstuvwxyzab", "abcdefghijklmnopqrstuvwxyzabc", "abcdefghijklmnopqrstuvwxyzabcd", "abcdefghijklmnopqrstuvwxyzabcde", "abcdefghijklmnopqrstuvwxyzabcdef", "abcdefghijklmnopqrstuvwxyzabcdefg", "abcdefghijklmnopqrstuvwxyzabcdefgh", "abcdefghijklmnopqrstuvwxyzabcdefghi", "abcdefghijklmnopqrstuvwxyzabcdefghij", "abcdefghijklmnopqrstuvwxyzabcdefghijk", "abcdefghijklmnopqrstuvwxyzabcdefghijkl", "abcdefghijklmnopqrstuvwxyzabcdefghijklm", "abcdefghijklmnopqrstuvwxyzabcdefghijklmn", "abcdefghijklmnopqrstuvwxyzabcdefghijklmno", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnop", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopq", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvw", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx" }) << " : 50\n";
	cout << oss.getLength({ "xyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu", "wxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst", "vwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs", "uvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr", "tuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopq", "stuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnop", "rstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmno", "qrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmn", "pqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklm", "opqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl", "nopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk", "mnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij", "lmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi", "klmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh", "jklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefg", "ijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef", "hijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcde", "ghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcd", "fghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabc", "efghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab", "defghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza", "cdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "bcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxy", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx", "zabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvw", "yzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv", "xyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu", "wxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrst", "vwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs", "uvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr", "tuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopq", "stuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnop", "rstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmno", "qrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmn", "pqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklm", "opqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl", "nopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk", "mnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij", "lmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi", "klmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh", "jklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefg", "ijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdef", "hijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcde", "ghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcd", "fghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabc", "efghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab", "defghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza", "cdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz", "bcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxy", "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx" }) << " : 1275\n";
	cout << oss.getLength({ "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww", "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv", "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu", "tttttttttttttttttttttttttttttttttttttttttttttttttt", "ssssssssssssssssssssssssssssssssssssssssssssssssss", "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr", "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq", "pppppppppppppppppppppppppppppppppppppppppppppppppp", "oooooooooooooooooooooooooooooooooooooooooooooooooo", "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn", "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm", "llllllllllllllllllllllllllllllllllllllllllllllllll", "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk", "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj", "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii", "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", "gggggggggggggggggggggggggggggggggggggggggggggggggg", "ffffffffffffffffffffffffffffffffffffffffffffffffff", "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", "dddddddddddddddddddddddddddddddddddddddddddddddddd", "cccccccccccccccccccccccccccccccccccccccccccccccccc", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz", "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx", "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww", "vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv", "uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu", "tttttttttttttttttttttttttttttttttttttttttttttttttt", "ssssssssssssssssssssssssssssssssssssssssssssssssss", "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr", "qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq", "pppppppppppppppppppppppppppppppppppppppppppppppppp", "oooooooooooooooooooooooooooooooooooooooooooooooooo", "nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn", "mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm", "llllllllllllllllllllllllllllllllllllllllllllllllll", "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk", "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj", "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii", "hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh", "gggggggggggggggggggggggggggggggggggggggggggggggggg", "ffffffffffffffffffffffffffffffffffffffffffffffffff", "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", "dddddddddddddddddddddddddddddddddddddddddddddddddd", "cccccccccccccccccccccccccccccccccccccccccccccccccc", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }) << " : 2500\n";
	cout << oss.getLength({ "rghkbwi", "ivorhalqkbqpqaeqeacboyejxxomi", "nhwphyjwbysksgullfvjsjzwaktsdfvqa", "vjsjzwaktsdfvq", "d", "zhlt", "kvloqsdoksbq", "vemdtdtocsmhpxrwdwpzvxegcubmfbnpntyqojgg", "vnwzgsylralekpkaoocfgfiqtwjxhemmkkbfrihxg", "nwzgsylralekpkaoocfgfiqtwjxhemmkkbfrihxgcjxakd", "etwbtathbjyvutvsaeoidxts", "tvsaeoidxtsqbbhulpbvgdlzilpath", "vz", "dmjtdvdzcy", "igycthymbvvfzuslkhugfwatpqhmwsxfes", "bvvfzuslkhugfwatpqhmwsxfesjxfpqogbpykostghngcox", "fesjxfpqogbpykostghngc", "jfodgjftohmljyelwmeovdahtfzfwyulkaqnhnxslsyic", "meovdahtfzfwyulkaqnhnxslsyicigodpkengfuxfxut", "odpkengfuxfxutrdeacvxgrrfnuukjjer", "ergsuxt", "c", "jekugycnpcvrhoqk", "qjszovdqammidbbnhf", "ovdqammi", "won", "msxlrfiewhdvypdyplducspjqpa", "spjqpaqyakidortqytvcvderwodzuwz", "ozepdsgqcs", "hoec" }) << " : 470\n";
	cout << oss.getLength({ "ioxennltbaqibvskinaepgelanr", "ednqpvrefnpnv", "tllilzmorkymtrvudy", "yppsbcybqphszhgnkzsdihlrzvcwhitrbjnqksmczlkhdlzt", "mhsc", "scuhdiidtmuldgiofhqdizgfcubnxtefpef", "xspopvshpsgiwsibms" }) << " : 160\n";
	cout << oss.getLength({ "nkxjpvfkwzaxoqhssjevqcgxdcbwfofyotcxmkdcenjpqfn", "xjpvfkwzaxoqhss", "sjevqcgx", "evqcgxdcbwfofyotcxmkdcenjpqfnsxwgxhhd", "dcbwfofyotcxmkdc", "bwfofyotcxmkdcenjpqfnsxwgxhhdyyvactmf", "enjpqfn", "fdngswpuzcyhqvwrnhnqabomgkzyibriguszn", "dngswpuzcyhqvwr", "puzcyhqvwrnhnqabomgkzy", "puzcyhqvwrnhnqabomgkzyibrigusznyjp", "cyhqvwrnhnqabomgkzyibrigusznyjpspwvn", "nhnqabomgkzyibrigusznyjpspwvnklspzqqnl", "hnqabomgkzyibrigusznyjpspwvnk", "abomgkzyib", "kzyibrigusznyjpspwvnklspzqqnlqrqxuzpy", "pspwvnklspzqqnlqrqxuzpynepmuh", "nklspzqqnlqrqxuzpynepmuhodcrao", "pzqqnlqrqxuzpynepmuhodcraotvegpclojockcurjcbbil", "nlqrq", "dcraotvegpclojockcurjcbbi", "r", "otvegpclojockcurjcbbilgajrmrwwdeyeaxgpcydaimagcy", "tvegpclojockc", "vegpclojockcurjcbbilgajrmrwwdeyeax", "urjcbbilgajrmrwwdeyeaxgpcydaimagcyhugfja", "wwdeyeaxgpcydaimagcyhugfja", "cydaimagcyhugfja", "cyhugfja", "fjas", "bczohdwxlkfxgilxjq", "kfxgilxjqhpzmvmarixhdxlfsaiibzubutefwthzlida", "ilxjq", "vmarixhdxlfsaiibzubutefwthzlidakgacdbnxgk", "ixh", "lfsaiibz", "dakgacdb", "dakg", "bnxgkwpcu", "kwpcubasptjjilwssjbfjgszqrfgkpqpfcyfgjm", "sptjjilwssjbfjgszqrfgkpqpfcyfg", "sjbfjgszq", "jgszqrfgkpqpfcyfg", "gszqrf", "zqrfgkpqpfcyfgj", "kpqpfcyfgjmblacflxcmtyhurxzc" }) << " : 308\n";
	cout << oss.getLength({ "jzjqfqbkyoulmtucuqrolzazagoifoomnopcopb", "zzzzhtxcytcgnzyvblczccx", "yxibstnramjqfvvvqpxrlrvzrhgwhcqyjpktngi", "qfvvvqpxrlrvzrhgwhcqyjpktngikkne", "knewemuokpbwvefgbdqnbdznczrxvbmytrfhgjb", "qkzefgqwurb", "rtwbhqydghiivcgpwjnhyuxsihbpsiedqaauikgyvzddksbk", "uxsihbpsiedqaauikgyvzd", "ssbmdhegllibrhcirilkhuyauemvvmktvbwt", "xljlczdghcwlqjzlfuxjwhklhvomtcazxq", "tcazxqmcrlkydpdentcjycyjjsdzjgcevmspiddeyt", "cevmspiddeytkvpajacskdzvwqoigvnqzgtxnhhm", "zgtxnhhmqvzlctgdezhuraeytrvvzvngbdfk", "ytrvvzvngbdfkavvjdmeihisiaubmgdetlau", "zzkeldhyqepaehyhefzbd", "zzkeldhyqepaehyhefzbdiroi", "d", "sfrizjrlyybhufomeodbysybzs", "zugtimihikhftprmcwpo", "zxgrsbqapabsodzlpkiujcrfckjc", "omlrcfvovr", "wgkcwtxwmcxojiyrevglkfbisrmtxwbvgslzwhxvwoyg", "f", "xbsdvneaxmexxexpypwgygosjckufmiuzrmwpmojdoqqbczxk", "xxe", "rjkgyphlcfzpsppkyty" }) << " : 606\n";
	cout << oss.getLength({ "hckkei", "inuqynqbscmomcmhdyqrvnrlxfkzis", "dyqrvnrlxfkzisyqzqediyp", "mqynryxsxzocusuodrdup", "eqp", "wgl", "qlcrqvwgaomdhltjxycmlaypbspoxahbqfyvudxvptwqvdo", "laypbspoxahbqfyvudxvptwqvdonxoufxo", "spoxahbqfyvudxvptwqvdonxoufxobsyiovbiwvrgkrj", "biwvrgkrjflb", "iwvrgkrjflbzhnzdmpljwwwptxfle", "avtseppicpenrgcxvpbtryyooabvngfoamipgpaejtg", "tryyooabvngfoamipgpa", "oamipgpaejtgwlealkbptzjnelhdtorn", "dmxprkkpqozqxq", "gttudeubpzwacjmibyrzbbhbmphdu", "tudeubpzwacjmibyrzbbhbmphdumrlf", "yjpsrjqnkjsjnlixsbjygpcxbsuuhdlacsfblqcehijq", "mvhdcyorqazgnsfrrajtmfjhdhrcvwfucfxeqswefkkgc", "zgnsfrrajtmfjh", "jtmfjhdhrcvwfucfxeqswefkkg", "tcoltdtbftizksonktzk", "evspueclekxwxmcacqpjmnoqymsfgriyhwboytpevod", "rrdubjfw", "as", "stabg", "wkurnnnvzzwxbjpbctlp", "awhjxzsbghzollfoeytuvsbdilolxtjldoxefzf", "vsbdilolxtjldoxefz", "hbkajoyfyjqqmlkqkjp", "abpkalmrdbxdlqjkndtadwlmg", "bxdlqjkndtadwlmgtxjsbkffcdrgt", "nlefamelwbpmihmd", "plpkxzitfynacwxinnulwjcquywl", "gmrasda", "wtm", "tynavoimylyeqfspaxndcopsoalkwpyxgbdkxjxystguaodh", "navoimylyeqfspaxndcopsoalkwpyxgbdk", "ckwcourszyghxbugncqgkbaqsgvumuj", "ropfsdjopmwykfwakgiaeubejfyvqtvvmbnhxjzfq", "cxceimsaibytxkaerezggnhtuuuvnmpiihdmyjs", "psfkrmr" }) << " : 773\n";
	cout << oss.getLength({ "riuufw", "riuufwajidxrdqggyycexvjkqfkigkiwvtyc", "riuuf", "ufwajidxrdqggyy", "ajidxrdqggyycexvjkqfkigkiwv", "idxrdqggyycexvjkqfkigkiwvtycouj", "dxrdqggyycexvjkqfk", "xrdqggyycexvjkqfkigkiwvtycoujijx", "xrdqggyycexvjkqfkigkiwvtycoujijxpblil", "xrdqggyycexvjkqfkigki", "rdqggyycexvjkqfkigkiwvtycoujijxpblilokay", "yycexvjkqfkigkiwvtyco", "yycexvjkqfkigkiwvtycoujijxpbl", "ycexvjkqfkigkiwvtycoujijxpblilokay", "cexvjkqf", "exvjkqfkigkiwvtycoujij", "exvjkqfkigkiwvtycoujijxpbliloka", "vjkqfkigkiwvtycoujijxpblilo", "kqfkigkiwvtycoujijxpblilokaybpuj", "igkiwvtycouj", "ycoujijxpblilokaybpujiieazyuw", "ycoujijxpbliloka", "oujijxpblilokaybpujiieazyuwsjinxcuynqng", "oujijxpblil", "gouj", "ijxpblilok", "okaybpujiieazyuwsjinxcuyn", "aybpujiieazyuwsji", "ybpujiieazyu", "pujiieazyuwsjinxcuynqn", "jiieazyu", "iieazyuwsj", "e", "eazyuwsjinxcuynqng", "azyuwsjinxcuy", "azyuwsj", "azyuwsjin", "ws", "jinxcuynqngo", "jinxcuynq", "xcu", "cuyqm", "c", "y", "qngoe", "ng", "nga" }) << " : 128\n";
	cout << oss.getLength({ "egvdkysxmyafhlqzqtgjprpxloplmiy", "sxlfiihvvgyvfkbqtvghtkweijz", "ihvvgyvfkbqtvghtkweijzotcvxwpotuatqqzydkuwy", "cfwbkpysvvpewrvgetbkooshgnniumnqmawqoedshvtl", "bkpysvvpewr", "hgbgjtedleshymicsf", "bdkdsr", "lxwbkjxnwzjcdlftkueidqwsqudeeinr", "nwzjcdlftkueidqwsq", "josuas", "ftwlrusizvktjlicydmumuqrfwxdkpxqoaorzndr", "itjexfsycqgxjztafotmbyvo", "kxeagmenboqhxkymxyttr", "uvurmghxdwihqcptfnwz", "ovonybdjcgyjuhsxp" }) << " : 307\n";
	cout << oss.getLength({ "plicxniaihdgeugmfpirbjqtkdybjlxbtuqiuetmyynxsovuv", "vuviduxd", "tv", "nb", "huwhvekpyxnuoruhagqkj", "tiyckjryrzdwpsfujxpwfhrxktslmvkwdrtqbovvcuepqlxy", "yckjryrzdwpsfujxpwfhrxktslmvkwdrtqbovvcuepqlxyk", "epqlxyknzely", "cotrmvnyxvzvwdewkxgzivnlpjyryvisrouqijsuzz", "jsuzzvptrtdqkafryojycqjdabgqkokcwn", "ojycqjdabg", "nzmjstcjprsmirpdecbbvbaeuopdkwzhglrqlf", "ecbbvb", "opdkwzhglrqlfa", "vzbqddlkzouxjvrptcesxxnvzr", "xnvzrvxakqhrc", "dasgokdfvhlmrsnzinlaibegvxyutcqioglofojjxgjavlrl", "gyzxinadzfomhikdeynsmyxjbfbsxhwybwg", "ikdeynsm", "hgnaihmccnlomizikdnukeyorssflxhjdgipvssuffuwwabld", "nukeyorssflxhjdgipvssuffu", "nukeyorssflxh", "eyorssflxhjdgipvssuffuwwabldnj", "brkikggqxjrrjerlqmwwdgtljqflz", "flzgtqytgvqqfcyrrdxageauqahytcvnaufjoezud", "qytgvqqfc", "fcyrrdxageauqahytcvnaufjoezudsgfktyzua", "mjfsmrtwftfnilmblm", "biztigmqxwsrrcxnzmzaujchnc", "tmucybobqwnesdbilvid", "sdbilvidyslbrbwfsklvlnivccxjwljyajkono", "mopbxqlgagmdczgdtplapfgoah", "naharlhzjwqcuavzhwqfzosd", "acwqlesvlqypixgcnsrfnhbgdxxhzuyqqes", "wq" }) << " : 665\n";
	cout << oss.getLength({ "awpzzeuzsoafyzvexgiraws", "ufakqduwbjlnfltldbxuavhvxwgnkhchhhwwgdzbdzcwx", "zoirrtqvkzzipyrs", "fvueaywtxjxohxnqivwjebmcacjsulwfr", "racrqhnyaahrjsoodoixhjitncjmvkitwadmpaflameyyzhe", "qygkpppyt", "magkzobkbsrctcwokedsgnhshaxwksohk", "ojtpsfu", "qywhbtnsradqpcwksybogbg", "mtxebwgvqhfmb", "xebwgvqhfmbmkwyyobyugwsqjiqrydeacxnysyaxs", "jiqrydeacxnysyaxstukupcbxolobpuay", "jgpi", "inrdalfwjkcnsbmqyizmckqmltpzdecpkugdvduuckhezx", "pqrpoxkrseygkyitskyooncyicuphjqkgdcryvoi", "seygkyitskyooncyicuphjqkgdcryvoioziplo", "yooncyicuphjqk", "iocvrmxzckk", "alrlytevthjtzjyfjtmjicymkqcr", "zjyfjtmjicymkqcrojbbxtbuoiserxbqrxuuyjzsnrzrg", "kqcrojbbxtbuoiserxbqrxuuyjzsnrzrgb", "rojbbxtbuoiserxbqrxuuyjzsnr", "zsnrcvkt", "cvkdtypuouyrbyyxwhxzsruapabicy", "pmqbxlnihyjozutfxatckfsjw", "mqbxlnihyjozutfxatckfsjwwmfkfronkvzjgiqikvukerii", "lskpfwlivuqffrwpmzyhmvwdhu", "jynpymcbmwsgvvdgfictyszpboqmiitxeqv", "shjmhjmxq", "hjmhjmxqcsxrmrwwjsfyvfcfmbonqr", "tagd", "tshsajjrqshpkpgc" }) << " : 658\n";
	cout << oss.getLength({ "uvgjgeeuu", "olnkfeouhcafrkruktegdtyjctdvonwnljekbqhiydnw", "lnkfeouhcafrkruktegdtyjctdv", "ktegdtyjctdvonwnljekbqhiydnwyyytguxjpwbn", "tegdtyjct", "dtyjctdvonwnljekbqhiydnwyyytguxjpw", "tdvonwnljekbqhiydnwyyytguxjpwbnjfgzrmguerfhxpm", "rmguerfhxpmfwgcaxgxvxwcggosqyn", "fheoyze", "fgqjvbxpmbftuuhfsjpumhs", "jvbxpmbftuuhfsjpumhsibmblwqod", "yhfasrsskrppszkcosnohyxvlnnsgrzhzstxy", "nohyxvl", "mtvkhjfehofalnezrvaobsh", "fa", "hezf", "vvtoaavdhdhczoramzwkwnruneqwhnjrwdud", "wnruneqwhnjrwdudcprohyazhcueeunxnzyjuxwyg", "uneqwhnjrwdudcprohyazhcuee", "rh", "vdvxbnijpotyvs", "lzwcodbw", "wcodb", "ssh", "yzttqxdaconmb", "box", "xygspgmxyf", "yfeggsxhxnzhvadyehcqbk", "oklswe", "lswexndytvpjihgxjmy", "scgclvmcpmddlaieossenqjzk", "bqyxsarpe", "drnrazgggihwqpo", "drnrazg", "rpscuncmrgrrxwuwsdhwgvvgqrkqrbplbz", "dhwgvvgqrkqrbplbzqmyzclvcr", "v", "ybiqwlgruvdcsdvseolhwwpnom", "eolhwwpnomsvrrcwtluxsbmeffyvtad", "jmndafhi", "peltcumshuszldrqvxumflddrgja", "rqvxumflddrgjamw" }) << " : 531\n";
	cout << oss.getLength({ "dexzldqzywu", "xzldqzywuliitderneyjlikdvgfasfxcihcilccskrgl", "dvgfasfxcihcilccskrg", "fasfxcihcilccskrglqnqwbmftuozcjbsamafgpklwxnclvds", "xcihcilccskrglqnqwbmftuozcjbsamafgpkl", "cskrglqnqwbmftuozcjbsamaf", "skrglqnqwbmftuozcjbsama", "bsama", "nclvdssxwwquibifdbeqmatqxhmhrcsehsnviwnqefft", "ifdbeqmatqxhmhrcsehsnviwnqe", "rmsircxayqmtebhgveooypltdrcjzrwuixcfhyki", "hgveooypltdrcj", "pltdrcjzrwuixcf", "uixcfhykiqsjekkgmensnucexosvswmimkrbih", "mimkrbihqmlvbfckpalukifxahwruhieleorobzdri", "mimkrbihqmlvb", "eorobzdrimbsemyhuovheuojxrwiyyxhsvkahyaqidzz", "iyyxhsvkahyaqidzzg", "zzgqsmpxwmzdbqxrgeaoyhxtcdpsaariqpceursfznmmtv", "wmz", "zdbqxrgeao", "qxrgeaoyhxtcdpsaa", "eaoyh", "mmtvhhopmgcgavklb", "upvfqajzmpldiekvvefskbaytopvlcngmijjbhcivfhecf", "fqajzmpldiekvvefskbay", "ekvvefskbaytopvlcngmijjbhcivfhecfzitjhkdbrg", "hcivfhecfzitjhkdbrgyegzaqlvh", "hsrz", "srzcuhqicimebaupqwnxgytbqsobnvnkkyh", "nx", "qsobnvnkkyhvqbwp", "qso", "qsola", "solan" }) << " : 421\n";
	cout << oss.getLength({ "bbbbabbeebecdcdbcdecaeccd", "cc", "ebcbbdecbdedbaebeebababebaaccacecddecedeceacacad", "cbbdec", "ede", "edbcbabbdadccddcdacacbeaeebbcbbbacade", "debccbccdedb", "accbabaececedbecdbaaabaeaeceeaeeadadbbdcca", "abecbecedcabacacdcdcbedec", "deccaeaaebcc", "dcbdebcddcabbceeaaccaaacdebaecbedaedd", "acbcbcba", "eedecceda", "be" }) << " : 251\n";
	cout << oss.getLength({ "eceecedccaddeebeadadbddcdbecadb", "edccaddeebeadadbddcdbecadbcacdcedcc", "caddeebead", "bddcdbecadb", "cbebdbadbeebdeeacdbaabc", "eeacdbaabccedccaadadbebeddcbbb", "aabccedccaadadbebeddcbbbeeadeecddaceacaead", "eeadee", "dbebeddcbbbeeadeecddaceacaeaddeeecacbddabda", "bebeddcbbbeeadeecddaceacaeaddeeec", "cacbddabdabcaddbcdcabcbdaebbbcdecddabeddbac", "bcaddbcdcabcbdaebbbcdecddabeddb", "ddbaceabcbaacceddbaecdabaddb", "bcbaa", "aecdabaddbedcdecceccbcdebbceb", "bcdebbcebbdedcdabdecedadeaedcaebebbdadcaaebcadd", "addbeaeaaedeabbceabdaaedabcdbcdbccdd", "dcadabeaedcabccaaaceabbdabcaedaead", "aaaceabbdabcaedaeadadaeedbdceeadecaabced", "aaa", "cabaeebebecacedabbcceabdaeccabebcaaaedcccade", "acedabbcceabdaeccabebcaaaedccc", "ab", "cabebcaaaedcccadeaebabebece", "edcccadeaebabebececadbb" }) << " : 401\n";
	cout << oss.getLength({ "baeedaecaedadcecdccaecacbeeb", "aedadcecdccae", "edcdbacdcc", "bddecedbdecbbddababaeaaabaebbacbaaeaeabcabce", "ababaeaaabaebbacbaaeaeabcabceeaaabc", "aeecdbbbabbeddadabeeeacdacbdecbcbdadbad", "cbdecbc", "deceeeaaeecaeabbbaabcacdaecadcbadad", "adcbadadeebceaabee", "ebbeabeaedabdddddeeeaaedebbeae", "ddeeeaaedebbeaea", "d", "baebaeaecdaddddccbeddcdeaadcedcabaab", "eaadcedcabaabebaa", "bbabecececcabdadcacebbcacadecbaeececeaccbdacae", "bcacadecbaeececeaccbdacaebbb", "ebbbcadceeeadecbdbcbaeaeb", "dabcbeeaeabcdbdaaebacbaaabbbcbcdaeecbcbedcebd", "edecceadddebecdcccbcaeadadeaedbdcdacddcebcaeb", "bedecbae", "edcccebcbddeabddbadacbaaddebedaecacebcaceda", "ccebcbddeabddba", "bedaecacebcacedaadceeceeac", "dce", "decbaabeddcbcdba", "cbaabbdaebdababacbbebcbbbbeacddebcbbbadecabd", "adbdbcdabdbaeeaceaddacdcebccebdeebbdcbdc", "bdbcdabdbaeeaceaddacdcebccebdeebbd", "dccbeddccabbecbaddbbebeacbebdcee", "acbebdceececdadaadaedabcbccceccccbbaddbdcebac", "baddbdcebacaedddadcabddaedbcd", "cedbdbbcdedeabdaeeaaceeeebcceebdbaecaddebeacca", "bdbaecaddebeaccadbec", "ac", "dbaaedaaabdedddecccdceeeabdcadedebdbe", "bdcadedebdbedebe", "ce" }) << " : 737\n";
	cout << oss.getLength({ "dadceecbdeccccaaedeeabeea", "daacceeabee", "c", "aecbdeeeaaebbcdaada", "ddaabeddddbedddecccbeceabadddbabcbaacdcebcbc", "eddddbedddecccbeceabadddbabcbaa", "eddddbedddecccbeceabadddbabcba", "dbabadbbaabeceeedebbbccadd", "eceeedebbbcc", "cbcdebabeaebdeaaabddaddbbeeeda", "bbddbeedcbddbade", "dbeedcbddbadeadcbbcdaededccdabccddcecbd", "ddbadeadcbbcdaededccdabccddcecbddaacadabbddaad", "daacadabbddaadeabeaaadeaabcdbeceedabbdbddbacabbba", "cdebaeedabcadbecccabbeac", "aedcdbdeccebacdaceadcedbaaad", "beebcbbbcddcecdcaab", "bcbbbcdd", "adbeeddecddebdbdebaacaddeebeacbbcddc", "dc", "eabceeacaadbcbababcccadaba", "abcccadabaa", "acabd" }) << " : 384\n";
	cout << oss.getLength({ "bcdbdddcccbeaebedddcebdbadceedaaabcad", "aae", "dadceabadbabccecdcbadbcadaece", "eebedabbdbcabdcdedbbabeeeaeecccbde", "ccbdebcccbddeabbccbbabeaadbdcececcccecdbbdea", "bdeabcdebedadeedaacdbcbdbbcedecddabdbebbaedda", "bcbabeaeddcaaaadececdeeaeedeacaaccabacda", "eaeedeacaaccabacdadcdeadbaeacaeadacebbcae", "bbeacccebb", "badadbeabbbebabdedccbbadedde", "cecdeedcabedcecd", "bbb" }) << " : 301\n";
	cout << oss.getLength({ "abddaedebededbacecdeadadcaaadcbbabbaacbedabbb", "debededb", "dcbbabbaacbedabbbbedccbbcacbdbacdb", "bedabbbbedccbbcac", "dccbbc", "cacbdbacdbbcbddcdaabcaad", "aabc", "dcbeebbcbdaedcabcc", "aedcabccabeabdb", "beadedbeaddbaedadbdc", "addbaedadbdcbcdebcbc", "baedadb", "abedaaeebeeaceadab", "bddbeddccb", "dccbabbbcddedeccbbddbbebcbaec", "bcddedeccbbddbbebcbaecbccccaebcdaadbcceeeccaea", "eacebadebdcaecaadcbabedde", "cebade", "dcb", "bdddeb", "bed", "acbdeeeaebaaccacaecedcbbbdddbcacce", "acaecedcbbbdddbcacce", "cedcbbbdddbcacceaeadecaadeaacebbdaddc", "bdddacdaccbaebdebcacedbbed", "acdaccbaebdebcacedbbedeaabbcabecbbddacadedccea", "accbaebdebcacedbbedeaabbcabecbbddac", "deaabbcabecbbddacadedcceaaeacdedaed", "eaabbcabecbbddacadedcceaaeacdedaedddbeba", "bddacadedcceaaeacdedaedddbebacbd", "dacadedcceaaeacdedaedddbe", "edcceaaeacdedaed", "edaedddbebacbdbecdcebbbaadbdeeceeeebc", "aedddbebacbdbecdcebbba", "ebcbeaeccacbabdcac", "cacbabdcacecacaabbcdecceaeceaec", "cacaabbcdecceaeceaecddaceacddbdccccecadaee", "ddaceacddbdccccecadaeeeb", "cadaeeebceabdeeb", "beecacecbdbcbadcacdadeacaaccbbeeecdebbbeca", "aceddacbcacaeaebbedbeebaccb", "cbbbd" }) << " : 519\n";
	cout << oss.getLength({ "cddacabcdbecdcbbdcbeabbacabbcbebda", "acabcdbecdcbbdcbeabbacabbcbebdabbdaaabdeb", "bdcccbcbdcacbe", "ccdaaadcabaceeae", "daaadcabaceeaeedccaabccccdbdcdacbbdbedebcdab", "cdacbbdbedebcdababebbdbcbecbdbccacdcbeadd", "bebbdbcbecbdbccac", "eceebeabaaadcbabbabccddebebadeecca", "cecbeabdbaaeeace", "cdddebcabd", "eaacebeccbac", "cdcdbbacacdaaabcdcadeccaecebccebcedadcd", "cbe", "ccaebdeaddedceeddaeeeecddaaeacbdedabbea", "ee", "dbbbbeeddeaedeceedecededaebbbeaceedbad", "edbadeaabbdacadadbceebcbc", "bdacadadbceebcbceedededcbccbbaece", "dbceebcbceedededcbccbbaecebdbaedbdeabeacbcdec", "eebcbceedededcbccbbaecebdbaedbdeabeacbcdecbadee", "baecebdbaedb", "cebdbaedbdeabeacbcd", "adbcd", "eaaaeabddceaceeeacdbe", "eaceeeacdbeacd", "ddcccbbabeceeeccbccbabbbeeccaaeaecbddcdab", "ccbccbabb", "b", "dbebabdeccabea", "eaeaaccdcabcddcaedeaac", "accdcabcddcaedeaa", "dd" }) << " : 482\n";
	cout << oss.getLength({ "baeaedbcaebcaaaabeacbeaceacaeaeadda", "eacaeaeaddaaecebcceaaabee", "eacaadddc", "adddccbdaaaaedcdacecebeeacacdadccaa", "abbcdceeeeadbaabdebabaddddcacaabbabcaca", "cddecadecbabcabbdeecabaae", "cecdccbbddcadceaaaeebb", "bdebacaecdcecebebeacbcbcabcdbcdabdcacae", "bbdeacaaeddacaeadbddbecbedbdebccbaac", "cedcebdbdeeedcbdeedcbccceeaeeebaeeeebcaeedbdadba", "deeabadcddeeebbebeeeaedceabbdeedbbdaacceedabeced", "edabecedaaecdaebcdceeeecacebededbdbedaed", "adaeaacbae", "dda", "aedb" }) << " : 389\n";
	cout << oss.getLength({ "dbd", "cbedecccebbbeab", "beccbceaaebacceceddabbede", "dbcedecaadaaecbceaaebbebcadeb", "ebcaeeccedbadeedddbdcaacdeabacddb", "ccedbadeedddbdcaacdeabacddbcc", "deabacddbccacdedbeabdebadeaeadaebeecebe", "cddbccacdedbeabdeb", "abecdbbdacaabecbeaadedbacbeabddddbaceccebd", "acbeabddddbaceccebdead", "aceccbecedc", "dcbacecdcbeadadeeabebdeaaac", "cdceb", "cebcaacadacecaaaedbddacedeedc", "abbceecbbddacdbccdecdaadadecad", "eecbbddacdbcc", "cbdeccd", "aceaddababecdeedabecdbeddbbaaceedcabdeecada", "cdeedabecdbeddbbaaceedcabdeecadabaeedbc", "cdeedabecdbeddbbaaceedcabdeecad", "deedaebeaaaeaaacdcbecddaaaddccdddca", "cabdbcdeebcdaeaccbbba", "eebcdaeaccbbbacbbcadebddebcaecbae", "bbaddceaaeadbabdbbabcddbcbdc", "eadbabdbbabcdd", "badecaacecceacdabbbdeebaaeccddebdebeeabebcecb", "acecceacdabbbd", "abebcecbbadeabbecabbeedddcacceebdcda", "cabbeedddcacceebdcdabdccbaadcdbebecebdcdcbace", "dccbaadcdbebecebdcdcbacebbdaddcbd", "dccbaadcdbebecebdc", "ccbaa", "dcacddecaebbeeebaebbbedaeedbcbba", "acabebecdebbceabdeeaeebbeceb", "eabdeeaeebbecebaebdaed", "eabdeeaeebbecebaebdaed", "eddcbddadebbeebdaebaeedeabcbabccebbbad", "bddadebbeebdaebaeedeab", "ee", "cbdabebcddcbbacee", "bbaceeebbaaabedbaab", "bbaaabe" }) << " : 669\n";
	cout << oss.getLength({ "caedddcadebddaacd", "edbcdaeddeaacdecbceabecabbbeabddd", "decceebaabaaaccddceecaeaadac", "deceaadeaaececb", "deaaececbeabcccabbdacaae", "baede", "beceeebbdedcdabbbdcabbbcdbceeeacabbecaebc", "dae", "daeaadbcaabaaceaceeddacadd", "ceeddacaddcaddddbacacdcbcddabe", "baeedcacbdbaceaadbcbedcacadebdadcaacbbbbd", "dee", "abecaabcbcbbcbcdaedbbddbecd", "deeaeabad", "bccbd", "cddabcbacacdebebecedbccaaddec", "aecccaaeecbcececaaadeeaaeaaeddebc", "deebdababcbb", "acadcdeaeeeadeacadecacceaabcccebcbdadaadadbd", "ebdeddaeaebcbabacdcdebbdbedaebccdcbcdeabddc", "ebcbabacdcdebbdbedaebccdcbcdeabddcedccccaaba" }) << " : 453\n";
	cout << oss.getLength({ "abbbaaaabababbbbaabbaaaababaaba", "baaaabababbbbaabba", "aaaabababbbb", "a", "bababbbbaabbaaaababaabaaaabbaaaaaba", "ababbbbaabbaaa", "aaaababaabaaaabbaaaaabaaaabbaabb", "aaaababaabaaaabbaaaaabaaaabbaabbaaaba", "aaabbaaaaabaaaabbaabbaaabababaaa", "abbaaaaabaaaabbaabbaaabababaaaa", "baaaabbaabbaaa", "abbaabbaaabababaaaabbabaaababaaaaabaabaa", "baabbaaabababaaaabbabaaababaaaaabaaba", "baabbaaabababaaaabbabaaababaaaaabaaba", "aabbaaabababaaaabbabaaababaaaaabaabaababbbb", "bbaaabababaaaabbabaaababaaaa", "bbaaabababaaaabbaba", "aabababaaaabbabaaababaaaaabaabaababbbbabab", "babaaaabbabaaababaaaaabaabaababbbbab", "aabab", "aababaaaaabaabaababbbbababbbaaabab", "aaabaabaababbbbababbbaaababababbb", "aabaabaababbbbababbb", "aababbbbab", "abbbbababbbaaababa", "abbbbababbbaaababababbbbaaabbabbbaaaabaaabbbabb", "bbbaaababababb", "ababbbbaaabbabbbaaaabaaabbbabbbbaabbabbbaaaab", "bbbbaaabbabbbaaaabaaabbbabbbbaabbabbbaa", "baaabbabbba", "babbba", "bbaaaabaaabbbabbbbaab", "aaabbbabbbbaabbabbbaaaab", "aabbbabbbbaabb", "aabbbabbbba", "aabbbabbbbaabbabbbaaaabbbababaaaaabaaaabbb", "babbbbaabbabbbaaaabbbababaaaa", "abbbbaabbabbbaaaabbbababaaaaabaaaab", "bba", "aaaabaaaa", "ab", "abbba", "aa" }) << " : 169\n";
	cout << oss.getLength({ "aabaaababbbbbaaaabbbabbbbabbbbababaaaabbabb", "abbbbabbbbababaaaa", "abbbbababaaaabbabbbaba", "bbbbaaaabaaaababbbb", "aabbabbabaaabaaabbaaababbabbbabbabbbabaabbbabaaa", "aaabaaabba", "a", "babaaababaaaaaabaabbabababbabbababbbaaabababab", "babaaaaaabaab", "aaaaabaabbabababbabbababbbaaabababababaabaab", "aababbbaababbbbaaaabbabaaabbbabbba", "ababaabaabaabbabaaaabaabbbaaa", "bbbaaaaabaaaaaaaabbbbbabaabb", "aaaaabaaaaaaaabbbbbabaabbbbbbaaaabbabbaabbbab", "baaaaaaaabb", "aa", "bababbbaaaabbabaabbbabaababbaaabbaabbbbbb", "babbbaa", "a", "abbaaabbaabbbbbbababababbaba", "abbaabbbbbbababababbabaaabaa", "bbaabbbbbbababababbabaaabaababbaabab", "a", "babbabaaabaababbaababbaabaaabbbba", "aabaaabbbbaabbbaabaabbbaaaba", "abaabbababaabbabbaaa", "bbaaababababaababa", "ababaababababababbbaabaab", "aababababababbbaabaabaabaabbbab", "aababababababbbaabaabaa", "aabbbabbbbbababbaaabaabbbbbbaa", "baaabaabbbbbb", "bbbbbbaa" }) << " : 434\n";
	cout << oss.getLength({ "baabbbabbbbbabbabaabaabbabbabbbbaababa", "abbaaba" }) << " : 44\n";
	cout << oss.getLength({ "baaaaaabbbabbbaaaabaaababbaa", "bbbabbbaaaabaaababbaabbbbbbaaababaaababbabba", "babbaabbbbbbaaababaaababbabbabbbbaabbabba", "babaaababbabba", "bbab", "aaaaaaaaaaaabaababababaaaaabaabbbaaababbaaab", "aaababbabaabaababbbbaaababbbaaaa", "bbbbbaaabb", "aaabbbbabbbbaaaaaabbabaaaabaaaaabaabbaaa", "abbbbababbbbabaabbaaabbaababbbbaababbbaa", "babaabbaaabbaab", "baababbbaabbaabababaababaaba", "aabbaabababaababaabaabbbababbbbab", "abaabaabbbababbbbababaabba", "aababbaabababbbbaabbabaaababbbaabaababaaaba", "bbaabb", "babbbaab", "aabaaababbbbabbabbbaaabaabaaababababaabaab", "bbb", "abbabbbaaabaabaaababababaabaabbbabbbaabaab", "abaabaaababababaab", "bbbaabaabbbba", "ababbba", "aaabbababaaaaaaabaaaaabbaaaabaabab", "aaabbaaaabaababaaabaaaabbababaaabbbbbabaaabbababa", "abaaaabbababaaabbbbbabaaabbabababbbbaaaabbabbbaa", "baaaabbababaaabbbbbabaaabbabababbbbaaaabbabbb", "c", "babbbaaabababbabbaaabbaababaaaa", "baaabababba", "abbabbaaabbaababaaaaaabaaabbbbbabbaaabaaab", "abbaaabbaababaaaa", "abbaababaaaaaabaaabbbbb", "bbbbabbbbbbbbaabaabaaabbabaabbbbaabbbaba", "baabaabaaabbabaabbbbaabbbabaaaaababbaabbaaaab", "aaaaababbaabbaaaabbbaabaaabb", "aaaaababbaabbaaaabbbaabaaabbabbaaaaaaababb", "aabaaabbabbaaaaaaababbababbbab", "aaaaaababbababbbabbababbbabbabaabaabbab", "aaaababbab", "bbbbbba", "babaabababaabbabbaaaaabaab", "abbaaabbbabbbbbaaababbbbbaabaabbaa", "abbbabbbbbaaababbbbb", "babbbbbaabaabbaaabaaaabaababb", "b", "aab" }) << " : 679\n";
	cout << oss.getLength({ "babaabbbaa", "abbbabbbbababaabaaaabbaabaabaabaabaaab", "bbabbbabababbaaabbabbaaabaababaabbbaaabbbab", "aba", "aaaaabaaaaaaaabbabbbbaababaabaabbaaa", "aaaa", "aaabbbbbaabbabbbbbbababbbabab", "baaaaababbbaaabbabbaabaab", "aaaaabbbaabbaabbabaaaaabaababbbbaba", "aaababbbbbbbbabaaaaababbaaaaaa", "aaaababbbbaabbbbbaabbbabbaabbbabaabbabbbbbababaab" }) << " : 284\n";
	cout << oss.getLength({ "aaaaabaaabaaabbaabbabbba", "baaaaaabbbbbabaaaababbbaabaabaababbbbaaaaaabb", "bbaaabaa", "bbbbbabbabbaaabbbabbaabbbabaaaaaa", "a", "aaaaaabbaaa" }) << " : 111\n";
	cout << oss.getLength({ "baaaaabbabbabaabaaaaab", "ab", "ba", "bbbbaabaaaaaaababbbaba", "abbbababbb", "babaab", "abaaabaabbbbbbabb", "abaabbbbaababbaaababb", "b", "aaabababa", "abaaababbaabbbbbaabbaaaa", "abaabbaaaaaabaaabbaaababaabbabbababbabaaaabbaabb", "baaaabbaabbaabbbbbaabaabbbabbabbbbab", "abbbaaaaaababaaaabbbabbbbbbabb", "ababaaabbabbbbaaabaaabbabbabbbaabaabbbbabaaabb", "bbabbbaabaabbbbabaaabbabbababbaaaabbaabbbbab", "babbbaabaabbbbabaaab", "abb", "abbbaaabbaaaaabaabbbababbabaabaabbabbabbbaababb", "babbbbbaaabaaabbbbaababbabbbbbababbabbba", "bbaabbaabaaab", "ababbbaabbababbbabbabababbabbaaabababb", "abbabbaaababab", "baabbbaaaaaababbbabbbabaab", "bbababababbaaabbaaabbaaaaababbaabbabbaababaaba", "aabaabbaaa", "bbbaaababbaaabbaabbbaabbbbaababababbabbabba", "aaaabbbbbbaabbabbaabbabaabaabbbaaaaabbb", "ba", "aaabbaabaaabaabbaa", "bbaaaabbababa", "abaaabbbbbbbbaabababbabaaabb", "abbbaababbababbabbbbbaabaababbb", "bbbbbaabaababbbbbaabbabaaabaabbbbabbabb" }) << " : 673\n";
	cout << oss.getLength({ "baabbabbaaaabab", "aabb", "aabbbabbaaaababaabbbaaabbbbabaaaaa", "abaaaaabbbaabbbababaabaaabaaaabbbabbaaabbaaabaaab", "abbaaabaaab", "abababb", "aabaaaababababbaaaabaaaaaabab", "ababbbaaabbbbbabaab", "bbbaaa", "baaaababbb", "baaaaaaabaaababbaabbaabbbbababbabab", "bababaabbbbabbbbabababaaaabbabbbbbab", "ababaabbbbabbbbabababaaaabbabbbbb", "bbabbbbbabaabaabaaaabbbbbabbaaa", "abaabaaaabbbbbabbaaababbbbb", "a", "bbbbaba", "ababbab", "baabbbbbabaabbabaabbabaabaaaaaabbbab", "babbaaabbbababbaaaababbbaa", "bbbaaab", "babbaaabbabbabaaabaababbaabbabbaaa", "abaaaabba", "bbab", "aaabaabbbaababababbbbaba", "babababbbbabababababbbabbabaabbbbabbbaaaabbbbbaa", "bbabbabaabbbbabbbaaaabbbbbaaaabababbaababaabbaba", "aaaabbbbbaaaabababbaababaabbabaaabaabbbbaaba", "aabb", "babbbabaabbb", "bbbaaabbaababbbaabbabbbbabaabbbbabaabaabbba", "abbabbbbabaabbbbabaabaabbbaaaaabaababaa", "abababbbba", "bbaabbaaaabbabbabaaabbbbabaaaabba", "baaaabbaaabbbbbaabbbbbbbaaaaabbabaababbaa", "aaabbaaabbbbbaabbbbbbbaaaaabbabaababbaabbbabbbbab", "abbaabbbabbbbababbbabaabbb", "bbababbbabaab", "aabb" }) << " : 598\n";
	cout << oss.getLength({ "bba", "b", "aaabbabbbabbaaabbabbabababbbbb", "babbaabaabbaaaabbaababaabaababbbbababbabbab", "abbbbababbaaaabaaabbbbbbaababba", "babbba" }) << " : 107\n";
	cout << oss.getLength({ "bbabbbabbbbabbbaabaabaabba", "bbabbbabbbbabbbaabaabaabbabba", "babbbabbbbab", "babbbabbbbabbb", "abbbabbbbabbbaabaabaabbabbabbbababba", "bbbabbbaabaabaabbabbabbbababbaabbbaaabbaaaba", "abbbaabaabaabbabbabbbababbaabbbaaab", "ab", "baabbabbabbbababbaabbbaaa", "aabbabbabbbababbaabbba", "bbabbabbbababbaabbbaaabbaaab", "babbbababbaabbbaaa", "babbbababbaabbbaaabbaaabaab", "ababbaabbbaaabbaaabaabbaababbbbbbaabaaaababababb", "babbaabbbaaabbaaabaabbaababbbbbbaabaaaa", "babbaabbba", "bbaabbbaaabbaaabaabbaababbbbbbaabaaa", "aabbbaaabbaaabaab", "abba", "abbaaabaabbaababbbbbbaabaaaababababbabaaabaab", "baaabaabbaababbbbbba", "aabaabbaababb", "aabbaab", "aababbbbbbaabaaaababababbabaaabaaba", "babbbbbbaaba", "aa", "b", "abaaaabababa", "ababbabaaabaabaabbbbabaaaaaabaaababbbb", "babbab", "abbabaaabaabaabbbb", "baaa", "ab", "abaabbbbabaa", "bbabaaaaaabaaababbb", "bbabaaaaaa", "aaa", "baaababbbbbb", "aaababbbbbb", "a", "bbbbb", "bb", "b", "b", "ab", "ba", "b", "bab", "baab" }) << " : 143\n";
	cout << oss.getLength({ "asd", "sdf", "dfg", "fgh", "hgj", "hjk", "jkl", "asd", "wqe", "zxc", "asd", "asd", "asd", "wqe", "sdaf", "hdgh", "xzc", "ahsdg", "wklqjl", "skladj", "xmc", "aklsjdlkajdlalkshfklalksh", "iwuoiklsajdkjldklalksdj", "mcnvaosd", "dfkjsghjkfh", "kjsdfdklsj", "asd", "kldsjfklsj", "jdkkd", "dsdsd", "dsdsds", "dsdsdsd", "dsdsklj", "kj", "kur", "mama", "ti", "deba", "pederast", "dolen", "da", "te", "eba", "v", "guza", "debel", "gaden", "dolen", "pedalski", "smachkan" }) << " : 231\n";
	cout << oss.getLength({ "a", "a", "b", "a" }) << " : 3\n";
	cout << oss.getLength({ "abc", "ca", "abc", "ab", "pa", "a", "abc", "pabc", "a", "bca", "cpa", "acp", "abccaabcabpaaabcpabcabcacpaacp", "abc", "ca", "abc", "ab", "pa", "a", "abc", "pabc", "a", "bca", "cpa", "acp", "xx", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaabcaaaa", "aaaaqq", "aaaaaqqqq", "aaaaaaaqqqqq", "qq" }) << " : 101\n";
	cout << oss.getLength({ "a", "aa", "aa", "aa", "aaaaaa", "aa", "aa", "aaaa", "aaa", "aa", "aa", "aaa", "a", "aaaaaaaaaaaa", "aaaaaaa", "aaaa", "aaa", "a", "aaaaaaaa" }) << " : 12\n";
	cout << oss.getLength({ "ababab", "ab", "ba", "ab", "ba", "ab", "ba" }) << " : 7\n";
	cout << oss.getLength({ "ab", "bc", "de", "ef", "abcdef" }) << " : 12\n";
	cout << oss.getLength({ "abcdef", "ab", "de", "bc", "ef" }) << " : 10\n";
	cout << oss.getLength({ "abcd", "bc" }) << " : 4\n";
	cout << oss.getLength({ "abcdef", "cde", "defgh", "g" }) << " : 8\n";
	cout << oss.getLength({ "abc", "ccc", "cde" }) << " : 7\n";
	cout << oss.getLength({ "abcdefg", "ab", "bc", "cd", "ef", "abcdef" }) << " : 13\n";
	cout << oss.getLength({ "baba", "babae", "bababae", "cererer", "cerer", "erer", "mnm", "n", "nm" }) << " : 22\n";
	cout << oss.getLength({ "abcdefg", "ab" }) << " : 7\n";
	cout << oss.getLength({ "a", "abss", "ss", "sa", "aab", "ac", "sobaka", "akkaunt", "aunter", "rres", "e", "kent" }) << " : 30\n";
	cout << oss.getLength({ "a", "ba", "a", "ba", "c", "cc", "ccc", "cccc", "cd", "ccd", "cc", "ccd", "ccdd", "ccddd", "ddd", "dbc", "ddbc", "dddbc", "dddb", "ddd", "dd", "d", "bc", "d", "dd", "ddd", "dd", "d", "ddw", "wbca", "www", "ww", "w", "bca", "wb", "wc", "wa", "aa", "aaa", "asdf", "sdf", "asd", "fd", "df", "ff", "f", "f", "d", "f" }) << " : 59\n";
	cout << oss.getLength({ "a", "aaa", "aaaaa" }) << " : 5\n";
	cout << oss.getLength({ "ab", "bc", "def", "ghi", "fghi" }) << " : 13\n";
	cout << oss.getLength({ "a", "b", "c", "abca", "bca" }) << " : 7\n";
	cout << oss.getLength({ "abcdes", "esf", "desesf" }) << " : 13\n";
	cout << oss.getLength({ "abc", "ca", "dsjfsdkhfskldhfls", "fasdas", "asdasdasdasdasdasdasd", "aaaaaaaaaaaaaaa", "fffffffffffffffffff", "asfasdasdqwedqwdqwsdascdasaw", "qwdqwddsdasdwdfqwfqwfefedf", "qwdqwddasddddddwq" }) << " : 148\n";
	cout << oss.getLength({ "ab", "bc", "bcdef", "abc", "abcde", "abcdf", "abcdefabcdeabcdfabcdef", "abc", "def", "bcdefa", "abcdefbc", "a", "b", "cd", "def", "bcdefcdefabc", "abcdefabcdef", "deabc" }) << " : 70\n";
	cout << oss.getLength({ "asgdhfjgueeejdhfffjdejdddrrfrfffrf", "rfffr", "fffrfrhdjfssdfdjjghhjjshhdhhdjfhhdj", "hdj", "asgaaaaa", "ga", "gaa", "sga", "aaaa", "gagagagaga", "afartaartaartaarta", "artartartart", "artartartart", "artartpa", "art", "popopoooooppopopo", "pooppopopopo", "popopopo", "opopopopo", "popop", "popop", "opopppoo", "oopp", "popopppop", "klklkllllkkkll", "hghghhghhghh", "hghhghhhghhghhghhghhghhhghhghhghhghghhg", "hghhhghhg", "ghh", "h", "hgh", "hgh", "ghg", "qopqopqop", "poqpoqpoq", "q", "p", "o", "opq", "pqo", "pq", "po", "asd" }) << " : 243\n";
	cout << oss.getLength({ "aaaaaaa", "ab", "c", "abc", "abcabccb", "aa", "aaeecdd" }) << " : 24\n";
	cout << oss.getLength({ "abc", "bcd", "abcd", "cde", "edg" }) << " : 11\n";
	cout << oss.getLength({ "abcdef", "ab", "bc", "de", "ef", "asdfg", "asrer", "erqwga", "asfd", "asg", "ad", "fa", "sdf", "asgas", "fa", "sf", "saf", "a", "wr", "sfasdfgagasdfasf", "asdfasdfag", "saf", "a", "fa", "sg", "z", "g", "a", "gasf", "as", "f", "asr", "wq", "r", "saf", "as", "fa", "sf", "w", "er", "wa", "r", "asf", "as", "f", "as", "r", "asfgasg", "ag", "a" }) << " : 122\n";
	cout << oss.getLength({ "aaaaa", "a" }) << " : 5\n";
	cout << oss.getLength({ "bcdefcdef", "fcde", "ef" }) << " : 9\n";
	cout << oss.getLength({ "a", "abcab", "ab", "abc", "bcabd", "abd" }) << " : 6\n";
	cout << oss.getLength({ "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij", "abcdefghijabcdefghijabcdefghijabcdefghijabcdefghij" }) << " : 50\n";
	cout << oss.getLength({ "abcdadfdfdsafdag", "gfadgfa", "gfdaaaaaa", "yut" }) << " : 34\n";
	cout << oss.getLength({ "a", "b", "ab", "b", "b" }) << " : 4\n";
	cout << oss.getLength({ "abcdef", "ab" }) << " : 6\n";
	cout << oss.getLength({ "ab", "a", "a" }) << " : 2\n";
	cout << oss.getLength({ "abcdef", "bc", "aefg" }) << " : 10\n";
	cout << oss.getLength({ "abc", "ca", "abc", "abc", "ca" }) << " : 7\n";
	cout << oss.getLength({ "abadc", "ad", "ab" }) << " : 7\n";
	cout << oss.getLength({ "abba", "ab", "ba" }) << " : 4\n";
	cout << oss.getLength({ "aaaaa", "a", "aaaaa" }) << " : 5\n";
	cout << oss.getLength({ "aaaaab", "ab", "aab" }) << " : 9\n";
	cout << oss.getLength({ "auewogisj", "isjeugs", "wogisjis", "auewo", "abc", "bc", "sauew", "klsigjekwwq", "sbc", "sbc", "sbc", "wplkwwq", "auewogisjisjeus", "sbcwplkww" }) << " : 78\n";
	cout << oss.getLength({ "abcdef", "abcd", "abc", "def", "lmnop", "mnop", "nop", "p", "qwertyu", "wertyu", "tyu", "yui", "hjkl", "jkl", "asdfgh", "fgh", "dfgh", "sdfghj", "fghjkl", "qwertyu", "tyuiop", "yuiop", "tiop", "opi", "iop", "klp", "lp", "qertyui", "rtyui", "poi", "oi", "qwerty", "yui", "uiop", "uiop", "abcd", "a", "b", "c", "d", "e", "f", "abcdef" }) << " : 93\n";
	cout << oss.getLength({ "a", "a", "a", "a", "a", "a", "a", "a" }) << " : 1\n";
	cout << oss.getLength({ "qqqqqqqqqqqqqqqqqqqqqqqq", "wwwwwwwwwwwwwwwwwwwwww", "eeeeeeeeeeeeeeeeeeeeeeeeeeee", "rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr", "tttttttttttttttttttttttttttttttttttttttt", "yyyyyyyyyyyyyyyyyyyyyyyy", "uuuuuuuuuuuuuuuuuuuuu", "iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii", "oooooooooooooooooooooooo", "pppppppppppppppppppp", "aaaaaaaaaaaaaaaaaaaa", "sssssssssssssssssssssss", "dddddddddddddddddddddd", "ffffffffffffffffffffffffffffffffff", "ggggggggggggggggggggggg", "hhhhhhhhhhhhhhhhhhhh", "jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj", "kkkkkkkkkkkkkkkkkkkkkkkkk", "llllllllllllllllllllllllllllllllll", "zzzzzzzzzzzzzzzzzzzzz", "xxxxxxxxxxxxxxxxxxxxx", "cccccccccccccccccccccccccc", "vvvvvvvvvvvvvvvvvvvvvvvvv", "bbbbbbbbbbbbbbbbbbbb", "bbbbt", "t", "yyuuu", "uu", "yu", "u", "iiiiiiiiiiiiiiiiiiiiii", "wwwwwwwwwwwwwwww", "eeeeeeeee", "qqqqqqq", "sssssss" }) << " : 709\n";
	cout << oss.getLength({ "abc", "acd" }) << " : 6\n";
	cout << oss.getLength({ "abc", "bcd", "cde", "cd" }) << " : 5\n";
	cout << oss.getLength({ "aabbcc", "bbcc", "bbcc" }) << " : 6\n";
	cout << oss.getLength({ "ab", "bc", "de", "ef", "abcdef", "def", "efg", "bcd", "abcdefgh" }) << " : 24\n";
	cout << oss.getLength({ "abacaba", "a", "ab", "aba", "bac", "acab", "abac", "aba", "c", "c", "cc", "c", "cc", "piko", "l", "pikol", "afonyayayayayayayaayayayayayayayaayayayayaayayaya", "afonyayayayayayayaayayayayayayayaayayayayaayayaya", "ayayayaayayayayayayayaayayayayaayayaya", "yaayayayayaayayaya", "aa", "abracadabra", "bra", "ra", "aa", "braa", "raaaaaa", "l", "q", "f", "sssssss", "alisa", "salisa", "alisa", "alisalisa", "dsfsdaf", "sdfasgrew", "sdfrweifdsgweriojufdlskjaiechawpaseunxfcafda", "eawfdsfeuwfdasf", "hgfhfgh", "safaeaefeawf", "dsafsdfghdsfhgs", "sdafasdfasdfsadfsad", "pika", "sdf", "pika", "aly", "yyy", "yyyy", "alyyyyyyy" }) << " : 262\n";
	cout << oss.getLength({ "abcab", "ca", "ab", "ca" }) << " : 7\n";
	cout << oss.getLength({ "mama", "ama", "aqo", "yq", "qo", "amaq", "amaq", "w", "w", "a", "a", "m", "a", "m", "fsd", "fg", "re", "rgdf", "g", "gs", "s" }) << " : 31\n";
	cout << oss.getLength({ "abcbc", "bc", "fg" }) << " : 7\n";
	cout << oss.getLength({ "moo", "opalllllllll", "lllll", "lalalalaa", "aalo" }) << " : 24\n";
	cout << oss.getLength({ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb" }) << " : 2450\n";
	cout << oss.getLength({ "abc", "defab", "abc" }) << " : 9\n";
	cout << oss.getLength({ "fadsafd", "sdsf", "fsadff", "sfafdsqr", "fadff", "dasfa" }) << " : 34\n";
	cout << oss.getLength({ "aab", "abcdefghij", "abcdefghijklmn" }) << " : 15\n";
	cout << oss.getLength({ "abcde", "bcx" }) << " : 8\n";
	cout << oss.getLength({ "ab", "aba", "abab" }) << " : 4\n";
	cout << oss.getLength({ "abcdef", "bcdefg" }) << " : 7\n";
	cout << oss.getLength({ "ababc", "abd" }) << " : 8\n";
	cout << oss.getLength({ "ab", "abcd", "bc", "ef", "bcd", "bc", "b", "bb", "hy", "hyy", "yyj", "yjkl", "yjkll", "kllty" }) << " : 20\n";
	cout << oss.getLength({ "abcdabc", "d", "ab" }) << " : 7\n";
	cout << oss.getLength({ "abc", "bca", "bc" }) << " : 4\n";
	cout << oss.getLength({ "abcd", "cdef" }) << " : 6\n";
	cout << oss.getLength({ "qwer", "qw", "ew", "rewq", "qwer", "rew", "we", "rew", "re" }) << " : 19\n";
	cout << oss.getLength({ "ab", "abc" }) << " : 3\n";
	cout << oss.getLength({ "a", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" }) << " : 50\n";
	cout << oss.getLength({ "mama", "ama", "aqo", "yq", "qo", "amaq", "amaq", "wwaw", "w", "w", "aajksjdk", "sjdajs", "saka", "skjhdao" }) << " : 41\n";
	cout << oss.getLength({ "auewogisj", "isjeugs", "wogisjis", "auewo", "abc", "bc", "sauew", "klsigjekwwq", "sbc", "sbc", "sbc", "wplkwwq", "auewogisjisjeus", "sbcwplkww", "kaowiejgksd", "kao", "kao", "qrst", "kaowiej", "kaqr", "wiejka" }) << " : 110\n";
	cout << oss.getLength({ "abc", "bc", "ab" }) << " : 5\n";
	cout << oss.getLength({ "abde", "bc", "de", "ef", "abcdef" }) << " : 15\n";
	cout << oss.getLength({ "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaaa", "aaaaaaaaaaaaaaa", "aaaaaaaaaaaaaa", "aaaaaaaaaaaaa", "aaaaaaaaaaaa", "aaaaaaaaaaa", "aaaaaaaaaa", "aaaaaaaaa", "aaaaaaaa", "aaaaaaa", "aaaaaa", "aaaaa", "aaaa", "aaa", "aa", "a" }) << " : 50\n";
	cout << oss.getLength({ "abcd", "cde" }) << " : 5\n";
	cout << oss.getLength({ "abcdefghijklmnopqrstuvwxyz", "klmnop", "nop", "pqr", "qrst" }) << " : 26\n";
	cout << oss.getLength({ "abababababcddfdfggf", "ababcd", "dfdf" }) << " : 19\n";
	cout << oss.getLength({ "abc", "abcd" }) << " : 4\n";
	cout << oss.getLength({ "abadce", "ad", "dc" }) << " : 6\n";
	cout << oss.getLength({ "dfazef", "zefff", "ffff", "azeggth", "g", "gth", "azz", "ertt", "tyhtyhjj", "hhh", "heh", "qsffsdffaf", "azzza", "a" }) << " : 50\n";
	cout << oss.getLength({ "abc", "def", "defg" }) << " : 7\n";
	cout << oss.getLength({ "abcdef", "abc" }) << " : 6\n";
	cout << oss.getLength({ "ab", "bc", "de", "ef", "abcdef", "abc", "cacc", "caaaaa", "aaaca", "acacac", "ac", "ca", "acac", "acrush", "rushendash", "dasho", "shodown" }) << " : 41\n";
	cout << oss.getLength({ "abc", "cd" }) << " : 4\n";
	cout << oss.getLength({ "abc", "b", "a" }) << " : 4\n";
	cout << oss.getLength({ "abcdef", "de", "ab" }) << " : 8\n";
	cout << oss.getLength({ "ab", "c", "abc", "ab", "c", "bc", "abc", "a", "a", "a", "abc", "c" }) << " : 11\n";
	cout << oss.getLength({ "abc", "a", "c", "b" }) << " : 4\n";
	cout << oss.getLength({ "abc", "qrstuv", "qrs" }) << " : 9\n";
	cout << oss.getLength({ "abcd", "ax" }) << " : 6\n";
	cout << oss.getLength({ "aaaaaaa", "ab", "c", "abc", "abcabccb", "aa", "aaeecdd", "cdsdfasgweaohi", "fcodsgf", "awegia", "asdgthh", "wegsdf", "dfsdgwedsf", "dfsdfsdfsdfdsfs", "dfsdfsdf", "dfsdfsdf" }) << " : 86\n";
	cout << oss.getLength({ "ab", "ac" }) << " : 4\n";
	cout << oss.getLength({ "abcdef", "def", "abc" }) << " : 9\n";
	cout << oss.getLength({ "abcecde", "cde", "ce" }) << " : 9\n";
	cout << oss.getLength({ "asdasdas", "asda", "asjhdk", "as", "asfdasdfasjfklasjlk", "asgfhgajsdfkgasdfasdfasdf", "asdfasda", "fdsa", "fd", "asdfghte", "sd", "asfdsa", "sdfasdhfgas", "asfasdfafefasd", "sdfcasd", "sd", "f", "fca", "sd", "ca", "s", "dc", "s", "d", "f", "we", "a", "s", "d", "fsd", "f", "asd", "asc", "sdc", "s", "dc", "sdfasdfasd", "f", "seas", "d", "fd", "fas", "f", "d", "fas", "af", "sa" }) << " : 158\n";
	cout << oss.getLength({ "bca", "cau" }) << " : 4\n";
	cout << oss.getLength({ "abab", "ab", "aba" }) << " : 4\n";
	cout << oss.getLength({ "asdf" }) << " : 4\n";
	cout << oss.getLength({ "abc", "ba", "ac" }) << " : 6\n";
	cout << oss.getLength({ "a", "a", "a", "a" }) << " : 1\n";
	cout << oss.getLength({ "abcdef", "ab", "bc", "de", "ef", "ininininty", "ininazz", "isininity", "init", "asdf", "dsfasgasdg", "zy", "yzyz", "yzyz", "annn", "nnv" }) << " : 56\n";
	cout << oss.getLength({ "ab", "bc", "de", "ef", "abcdef", "ef", "f", "f", "f", "f", "f", "g", "g", "rt", "rte", "rrd", "ered", "d", "d", "d", "d", "d", "d", "d", "ppp", "po", "opo", "o", "o", "o", "o", "oytutyu", "fg", "ggg" }) << " : 39\n";
	cout << oss.getLength({ "abcd", "bc", "efg", "ef", "efgh", "aaaaaaaaa" }) << " : 17\n";
	cout << oss.getLength({ "abcd", "cd", "bc" }) << " : 6\n";
	cout << oss.getLength({ "aabbcc", "abc" }) << " : 9\n";
	cout << oss.getLength({ "abdef", "abc" }) << " : 8\n";
	cout << oss.getLength({ "abcd", "bcde" }) << " : 5\n";
	cout << oss.getLength({ "abcdef", "abcyui" }) << " : 12\n";
	cout << oss.getLength({ "bac", "baa" }) << " : 6\n";
	cout << oss.getLength({ "maria", "rihana", "ariana", "ana", "a", "n" }) << " : 16\n";
	cout << oss.getLength({ "aaa", "a" }) << " : 3\n";
	cout << oss.getLength({ "abcdef", "ef", "ab" }) << " : 8\n";
	cout << oss.getLength({ "aaaaaaaaa", "aa", "aaaaaabbb" }) << " : 12\n";
	cout << oss.getLength({ "abc", "cde", "efg", "ghi" }) << " : 9\n";
	cout << oss.getLength({ "bc", "ef", "abcdef", "ab", "de" }) << " : 10\n";



	return 0;
}